name: Deploy Node Application

on:
  push:
    branches: [feature]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "OWNER_EMAIL=${{ secrets.OWNER_EMAIL }}" >> .env
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSSWORD }}
      - name: Build docker image
        run: docker build -t basith7618/nodejs-app .
      - name: Publish image to dockerhub
        run: docker push basith7618/nodejs-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from dockerhub
        run: docker pull basith7618/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container || true
      - name: Run docker container
        run: |
          docker run -d \
          -p 5000:5000 \
          -p 443:443 \
          -v /etc/letsencrypt:/etc/letsencrypt:ro \
          --name nodejs-app-container \
          basith7618/nodejs-app
